name: mobile
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you plan to publish it.

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^2.17.2         
  firebase_messaging: ^14.0.0    

  dio: ^5.0.0 
  


  flutter_screenutil: ^5.0.4+1 
  responsive_builder: ^0.5.0 

  provider: ^6.0.5

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.3.0
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true

  # To add assets, you can define them here:
  assets:
     - assets/
   

  # For adding custom fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
